version: '3'

services:

 influx-db:
  container_name: influxdb
  image: "influxdb:alpine"
  restart: unless-stopped
  volumes:
   - ./data/influx:/var/lib/influxdb2
  ports:
   - 8086:8086
  environment:
   - DOCKER_INFLUXDB_INIT_MODE=setup
   - DOCKER_INFLUXDB_INIT_USERNAME=admin
   - DOCKER_INFLUXDB_INIT_PASSWORD=supersecretpassword
   - DOCKER_INFLUXDB_INIT_ORG=home
   - DOCKER_INFLUXDB_INIT_BUCKET=home
 
 nodered:
  container_name: nodered
  image: "nodered/node-red:latest-18-minimal"
  restart: unless-stopped
  volumes:
   - ./data/nodered:/data
  ports:
   - 1880:1880
 
 python:
  container_name: python-service
  image: "python:3.9-bullseye"
  restart: unless-stopped
  working_dir: /app
  volumes: 
   - ./requirements.txt:/app/requirements.txt
   - ./main.py:/app/main.py
   - ./src:/app/src
  ports:
   - 5000:5000
  command: 
   - sh
   - -c 
   - "id -u devuser || adduser --disabled-password --gecos '' devuser && chown -R devuser /app && su devuser -c 'pip install --user -r /app/requirements.txt && python /app/main.py'"